apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gjh0
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0012-tenant/tkrw-pr712-0075-0012-app/devfile-sample-gjh0@sha256:f3f0bcbd97888c89f893d00f060a5f7d13d7c9b48bbafc60efcbe55203261e8f
        name: my-nodejs
        resources: {}
status: {}
